export const MOVIE_SEARCH_REQUEST = 'MOVIE_SEARCH_REQUEST';
export const MOVIE_SEARCH_SUCCESS = 'MOVIE_SEARCH_SUCCESS';
export const MOVIE_SEARCH_FAILURE = 'MOVIE_SEARCH_FAILURE';
export const MOVIE_GET_REQUEST = 'MOVIE_GET_REQUEST';
export const MOVIE_GET_SUCCESS = 'MOVIE_GET_SUCCESS';
export const MOVIE_GET_FAILURE = 'MOVIE_GET_FAILURE';
